apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  labels:
    - name: nginx-pod
      tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
